Update update-index.yml

diff --git a/.github/workflows/update-index.yml b/.github/workflows/update-index.yml
--- a/.github/workflows/update-index.yml
+++ b/.github/workflows/update-index.yml
@@ -23,6 +23,27 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Debugging: Check if files exist
+      run: |
+        # Check if both files exist
+        echo "Checking for files"
+        if [ ! -f "index_.md" ]; then
+          echo "index_.md not found!"
+          exit 1
+        fi
+        if [ ! -f "publications.md" ]; then
+          echo "publications.md not found!"
+          exit 1
+        fi
+        echo "Both files exist!"
+
+    - name: Debugging: Print content of index_.md and publications.md
+      run: |
+        echo "index_.md content:"
+        cat index_.md
+        echo "publications.md content:"
+        cat publications.md
+
     - name: Update index file with publications
       run: |
         # Read contents of publications.md
@@ -31,11 +52,20 @@ jobs:
         # Read the content of index_.md and insert publications_content at the placeholder
         index_content=$(cat index_.md)
 
+        # Check if the placeholder exists in index_.md
+        if [[ "$index_content" == *"<!-- publications -->"* ]]; then
+          echo "Placeholder found in index_.md."
+        else
+          echo "Placeholder <!-- publications --> not found in index_.md."
+          exit 1
+        fi
+
         # Replace the placeholder <!-- publications --> with the actual content of publications.md
         updated_index_content=$(echo "$index_content" | sed "s|<!-- publications -->|$publications_content|")
 
         # Write the updated content to index.md
         echo "$updated_index_content" > index.md
+        echo "index.md has been updated."
 
     - name: Commit and push changes
       run: |
